/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ycx_jnidemo_CallBack */

#ifndef _Included_com_ycx_jnidemo_CallBack
#define _Included_com_ycx_jnidemo_CallBack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ycx_jnidemo_CallBack
 * Method:    JNICallVoidJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ycx_jnidemo_CallBack_JNICallVoidJava
  (JNIEnv *, jobject);

/*
 * Class:     com_ycx_jnidemo_CallBack
 * Method:    JNICallIntJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ycx_jnidemo_CallBack_JNICallIntJava
  (JNIEnv *, jobject);

/*
 * Class:     com_ycx_jnidemo_CallBack
 * Method:    JNICallStringJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ycx_jnidemo_CallBack_JNICallStringJava
  (JNIEnv *, jobject);

/*
 * Class:     com_ycx_jnidemo_CallBack
 * Method:    JNICallToastJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ycx_jnidemo_CallBack_JNICallToastJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
