/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ycx_jnidemo_Test */

#ifndef _Included_com_ycx_jnidemo_Test
#define _Included_com_ycx_jnidemo_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ycx_jnidemo_Test
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ycx_jnidemo_Test_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_ycx_jnidemo_Test
 * Method:    postInteger
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ycx_jnidemo_Test_postInteger
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ycx_jnidemo_Test
 * Method:    postString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ycx_jnidemo_Test_postString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ycx_jnidemo_Test
 * Method:    postIntArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_ycx_jnidemo_Test_postIntArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
